### ISSUE TITLE
Add Keybind to add/remove items

### ISSUE THREAD

**Issue by SterlingHeaton** [Spyxar/GlowUp#1]
**Description**:
Add a configurable keybind to add/remove items from the glow list. Clicking the keybind while holding an item should add it to the glow list, if it is already on the list, then remove it. Should also send a chat message stating if the item was added or removed. This can streamline the process of adding items to the list without making it tedious. This also allows for quickly adding/removing temporary items to the glow list while harvesting from a farm or making sure they picked up everything when cleaning up.

**Example**:
Default key: G
The player holds a diamond in their main hand and presses G. Diamonds aren't part of the list, so the mod adds it and sends a chat message to the player stating that Diamonds were added.

The player throws diamonds on the ground and sees that they are now glowing.

The player holds a diamond in their main hand again and presses G. Diamonds are on the list, so the mod removes it and sends a chat message to the player stating that Diamonds were removed.

The player throws diamonds on the ground again and sees that they are no longer glowing.

**Comment by Spyxar** [comment]
Sounds good! I'll have a look at this and probably release it sometime this week

**Comment by Spyxar** [comment]
Just uploaded the new version (1.1.0) on here and Modrinth, if you find any issues (or want to suggest something) please reach out!

**Comment by Spyxar** [comment]
Uploaded v1.1.1 which should fix a crash on launch, the mod does now require fabric-api to be installed though.

**Comment by SterlingHeaton** [comment]
Awesome, it works great; thanks for being so quick to add this!
